name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_sqlite
    - name: Install composer dependencies
      run: composer install --no-interaction --prefer-dist
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse -c phpstan.neon || true
    - name: Run tests
      run: vendor/bin/phpunit --colors=always
